---

# This playbook runs the setup process for Arvados on a total of eight hosts.

- name: Update and upgrade packages
  hosts: arvados_hosts
  become: true

  tasks:
  - name: Update and upgrade
    apt:
      update_cache: yes
      upgrade: dist

- name: Add Arvados repos
  hosts: arvados_hosts
  become: true

  roles:
    - repos

- name: Add Arvados config
  hosts: arvados_hosts
  become: true

  roles:
    - config

- name: Install Postgres
  hosts: arvados-postgres
  become: true

  roles:
    - postgres
    
- name: Setup API / controller
  hosts: arvados-api
  become: true

  roles:
    - arvados-api

- name: Setup Keepstore 0
  hosts: arvados-keep0
  become: true

  roles:
    - arvados-keep0

- name: Setup Keepproxy, Keep-web, Keep-Balance
  hosts: arvados-keep
  become: true

  roles:
    - arvados-keep

- name: Restart API / controller software
  hosts: arvados-api
  become: true

  tasks:
  - name: Restart nginx
    systemd:
      name: nginx
      state: restarted

  - name: Restart arvados-controller
    systemd:
      name: arvados-controller
      state: restarted

- name: Install WS server
  hosts: arvados-ws
  become: true

  roles:
    - arvados-ws

- name: Install Workbench
  hosts: arvados-workbench
  become: true

  roles:
    - arvados-workbench

- name: Install Workbench2
  hosts: arvados-workbench2
  become: true

  roles:
    - arvados-workbench2

- name: Restart API / controller software
  hosts: arvados-api
  become: true

  tasks:
  - name: Restart nginx
    systemd:
      name: nginx
      state: restarted

  - name: Restart arvados-controller
    systemd:
      name: arvados-controller
      state: restarted