---

# This playbook starts the setup process for Arvados.

- name: Add Arvados repos
  hosts: domain_join
  become: true

  roles:
    - repos

- name: Add Arvados config
  hosts: domain_join
  become: true

  roles:
    - config
