---

# This playbook runs the setup process for Arvados on a total of eight hosts.

- name: Add Arvados repos
  hosts: arvados_hosts
  become: true

  roles:
    - repos

- name: Add Arvados config
  hosts: arvados_hosts
  become: true

  roles:
    - config

- name: Install Postgres
  hosts: arvados-postgres
  become: true

  roles:
    - postgres
    
- name: Setup API / controller
  hosts: arvados-api
  become: true

  roles:
    - arvados-api
