---

# This playbook starts the setup process for Arvados.

- name: Add Arvados repos
  hosts: arvados_hosts
  become: true

  roles:
    - repos

- name: Add Arvados config
  hosts: arvados_hosts
  become: true

  roles:
    - config

- name: Install Postgres
  hosts: arvados-postgres
  become: true

  roles:
    - postgres

