---

# This playbook joins machines to Broken.Works AD.

- name: Update and upgrade
  hosts: arvados_hosts
  become: true
  
  tasks:
  - name: update and upgrade
    apt:
      update_cache: yes
      upgrade: dist

- name: Apply common configuration
  hosts: arvados_hosts
  become: true

  roles:
    - common

- name: Apply configuration to newly deployed machines
  hosts: arvados_hosts
  become: true

  roles:
   - domain_join
