- name: "Install Keepstore"
  apt:
    name: "keepstore"
    state: present

- name: "Enable and restart Keepstore"
  ansible.builtin.systemd:
    name: 'keepstore'
    enabled: yes
    state: restarted