- name: "Install Crunch Local"
  apt:
    name: "crunch-dispatch-local"
    state: present

- name: "Install Crunch config file"
  template:
    src: crunch-dispatch-local-credentials.j2
    dest: /etc/arvados/crunch-dispatch-local-credentials
    mode: 0644

- name: "Install Arvados tools (including packages from cloud image described in https://github.com/arvados/arvados/blob/main/tools/compute-images/scripts/base.sh)"
  apt:
    pkg:
      - curl
      - git
      - build-essential
      - libcurl4-openssl-dev
      - python3-arvados-python-client
      - crunch-run
      - arvados-docker-cleaner
      - docker.io
      - ruby
      - ruby-dev
      - bundler
      - python3-arvados-cwl-runner
      - python3-arvados-fuse
      - openssh-server
      - apt-utils
      - curl
      - libcurl3-gnutls
      - libcurl4-openssl-dev
      - lvm2
      - cryptsetup
      - xfsprogs
    state: present
    update_cache: true

- name: "Remove unattended-upgrades"
  apt:
    name: unattended-upgrades
    purge: yes
    state: absent

- name: "Create Docker cleaner dir"
  file:
    path: /etc/arvados/docker-cleaner
    state: directory
    mode: '0755'

- name: "Create Docker cleaner config file"
  copy:
    dest: /etc/arvados/docker-cleaner/docker-cleaner.json
    content: |
      Quota: 10G
      RemoveStoppedContainers: always

- name: "Enable cgroup accounting"
  command: sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"/g' /etc/default/grub

- name: "Alter systemd unit file for Docker"
  copy:
    dest: /etc/systemd/system/docker.service
    content: |
      [Unit]
      Description=Docker Application Container Engine
      Documentation=https://docs.docker.com
      After=network-online.target firewalld.service containerd.service
      Wants=network-online.target
      Requires=docker.socket
      Wants=containerd.service

      [Service]
      Type=notify
      # the default is not to use systemd for cgroups because the delegate issues still
      # exists and systemd currently does not support the cgroup feature set required
      # for containers run by docker
      ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --default-ulimit nofile=10000:10000
      ExecReload=/bin/kill -s HUP $MAINPID
      TimeoutSec=0
      RestartSec=2
      Restart=always

      # Note that StartLimit* options were moved from "Service" to "Unit" in systemd 229.
      # Both the old, and new location are accepted by systemd 229 and up, so using the old location
      # to make them work for either version of systemd.
      StartLimitBurst=3

      # Note that StartLimitInterval was renamed to StartLimitIntervalSec in systemd 230.
      # Both the old, and new name are accepted by systemd 230 and up, so using the old name to make
      # this option work for either version of systemd.
      StartLimitInterval=60s

      # Having non-zero Limit*s causes performance problems due to accounting overhead
      # in the kernel. We recommend using cgroups to do container-local accounting.
      LimitNOFILE=infinity
      LimitNPROC=infinity
      LimitCORE=infinity

      # Comment TasksMax if your systemd version does not support it.
      # Only systemd 226 and above support this option.
      TasksMax=infinity

      # set delegate yes so that systemd does not reset the cgroups of docker containers
      Delegate=yes

      # kill only the docker process, not all processes in the cgroup
      KillMode=process
      OOMScoreAdjust=-500

      [Install]
      WantedBy=multi-user.target

- name: "Create config dir for FUSE"
  file:
    path: /etc/fuse
    state: directory

- name: "Set user_allow_other for FUSE"
  copy:
    dest: /etc/fuse/fuse.conf
    content: |
      user_allow_other

- name: "Set user_allow_other for FUSE"
  copy:
    dest: /etc/fuse.conf
    content: |
      user_allow_other

- name: "Add Crunch user"
  user:
    name: crunch
    password: '*'

- name: "Make Crunch user able to sudo with no password"
  copy:
    dest: /etc/sudoers.d/91-crunch
    content: |
      crunch ALL=(ALL) NOPASSWD:ALL

- name: "Update grub"
  command: update-grub

- name: "Enable and start Docker"
  systemd:
    name: docker
    enabled: yes
    state: restarted

- name: "Enable and start Docker cleaner"
  systemd:
    name: arvados-docker-cleaner
    enabled: yes
    state: restarted

- name: "Enable and start Crunch Local"
  ansible.builtin.systemd:
    name: 'crunch-dispatch-local'
    enabled: yes
    state: restarted
