- name: "Install Websocket Server"
  apt:
    name: "arvados-ws"
    state: present

- name: "Enable and start Websocket Server"
  ansible.builtin.systemd:
    name: 'arvados-ws'
    enabled: yes
    state: started